# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "hugo-theme-typography"
license = "MIT"
licenselink = "https://github.com/lpgph/hugo-theme-typography/blob/master/LICENSE"
description = ""
homepage = "https://github.com/lpgph/hugo-theme-typography"
tags = [
  "hugo",
  "theme",
  "blog",
  "clean",
  "responsive",
]
features = [
  "cover-image",
  "favicon",
  "pjax",
  "multilingual",
  "pagination",
  "social-menu",
  "syntax-highlighting",
  "SEO Optimized"
]
min_version = "0.62"

[author]
  name = "lpgph"
  homepage = "https://lpgph.github.io"



