[outputs]
  home = [ 'RSS', 'HTML' ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = 'application/rss'
    baseName = 'feed'

[Params]
  CreateDate = '2017-01-07T00:00:00Z'  # 建站时间
  Description = '勿以时穷而忘节，勿以势起而乱性'

  Favicon = 'img/favicon.ico'

  DateFormat = '2006-01-02'
  MonthFormat = '2006-01'
  FancyBox = true
  CreativeCommons = true
  MathJax = true
  # 代码高亮格式
  HighLightStyle = 'github'
  #paginateOriginalStyle = true
  # 首页展示内容
  mainSections = ["posts"]

  [Params.Live2dWidget]
    Model = 'https://lpgph.github.io/lib/live2d-widget/model/kesyoban/kesyoban.model.json'
    Dialog = true
    [Params.Live2dWidget.Mobile]
      show = false  # 是否在移动设备上显示
      scale = 0.5  # 移动设备上的缩放

  [Params.Valine]
    appId = 'l9ft1z7kmQ2kmWpnHxu0YcUi-gzGzoHsz'
    appKey = 'APUD0UjlIdDtY60wp9yArP6l'
  # [Params.Gitalk]
  #   language = 'zh-CN'
  #   clientID = '86c61da5bfaea99e9f10'
  #   clientSecret = '3c0524cd32fbe175601f5b964c6a34b6d31b0975'
  #   repo = 'lpgph.github.io'
  #   owner = 'lpgph'
  #   admin = ['lpgph']
  #   distractionFreeMode = false


  [Params.Archive]
    page = 20

[Menu]
  [[Menu.Main]]
    Name = 'home'
    identifier = "home"
    # post = "<span class='alert'>New!</span>"
    # pre = "home"
    URL = '/'
    weight = 1
  [[Menu.Main]]
    Name = 'archive'
    identifier = "archive"
    # post = "<span class='alert'>New!</span>"
    # pre = "archive"
    URL = '/posts/'
    weight = 2
  [[Menu.Main]]
    Name = 'notes'
    identifier = "notes"
    # post = "<span class='alert'>New!</span>"
    # pre = "sticky-note"
    URL = '/notes/'
    weight = 3
  [[Menu.Main]]
    Name = 'photos'
    identifier = "photos"
    # post = "<span class='alert'>New!</span>"
    # pre = "photo"
    URL = '/photos/'
    weight = 4
  [[Menu.Main]]
    Name = 'categories'
    identifier = "categories"
    URL = '/categories/'
    weight = 5
  [[Menu.Main]]
    Name = 'tags'
    identifier = "tags"
    URL = '/tags/'
    weight = 6
  [[Menu.Main]]
    Name = 'about'
    identifier = "about"
    # post = "<span class='alert'>New!</span>"
    # pre = "user"
    URL = '/about/'
    weight = 7

# full top bottom left right 

# [related]
#   threshold= 80
#   includeNewer= false
#   toLower= false
#   [indices]
#   - name: keywords
#     weight: 100
#   - name: date
#     weight: 10