baseURL = "https://example.org/"
title = "活版印字"
theme = "../"
# cd exampleSite && hugo server --themesDir .. --theme .
copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)"

hasCJKLanguage = true
defaultContentLanguage = "zh"

[languages.zh]
  languageName = "Chinese (Simplified)"
  languageCode = "zh-Hans"
  languageDirection = "ltr"

mainSections = ["posts"]
paginate = 2
paginatePath = "page"
enableEmoji = false
enableRobotsTXT = true
enableGitInfo = false # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。

# disqusShortname = ""
# googleAnalytics = ""

# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
# pygmentsStyle = "default"
#pygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
# pygmentsUseClasses = true # Use CSS classes to format highlighted code
#pygmentsCodefencesGuessSyntax = true
#pygmentsOptions = "linenos=table"

#[taxonomies]
# author = "author"
# tag = "tags"
# category = "categories"
#  note = "note"

#disableKinds = ["taxonomyTerm"]

[author]
  name = "loikein"

[social]
  Twitter = "example"
  GitHub = "example"
  Facebook = "example"
  LinkIn = "example"

[markup.highlight]
  style = "friendly"       # https://xyproto.github.io/splash/docs/all.html

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = [ 'RSS', 'HTML' ]

[services.rss]
  limit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量

[outputFormats]
  [outputFormats.RSS]
    mediatype = 'application/rss'
    baseName = 'feed'

[Params]
  CreateDate = "2024-06-01T02:36:49+0100"
  Description = 'Typography'
  copyright = '[BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)'
  Favicon = 'favicon.ico'

  themeColor = "ocean"
  # choose from:
  # light: ocean (original), forest, plum, misty, polka
  # dark: velvet, idea, window, cocoa

  search = true
  NoIndex = false

  DateFormat = '2006-01-02'
  MonthFormat = '2006-01'
  FancyBox = true
  CreativeCommons = true
  MathJax = true
  # 代码高亮格式
  HighLightStyle = 'github'
  #paginateOriginalStyle = true
  # 首页展示内容
  mainSections = ["posts"]

  [Params.Waline]
    serverURL = ''

  # [Params.Gitalk]
  #   language = 'zh-CN'
  #   clientID = ''
  #   clientSecret = ''
  #   repo = ''
  #   owner = ''
  #   admin = ['']
  #   distractionFreeMode = false

  [Params.Archive]
    page = 20   # number of posts per page in condensed archive (list) layout

[Menu]
  # [[Menu.Main]]
  #   Name = 'home'
  #   identifier = "home"
  #   # pre = "home"
  #   URL = '/'
  #   weight = 1
  [[Menu.Main]]
    Name = 'archive'
    identifier = "archive"
    # pre = "archive"
    URL = '/posts/'
    weight = 2
  [[Menu.Main]]
    Name = 'notes'
    identifier = "notes"
    # pre = "sticky-note"
    URL = '/notes/'
    weight = 3
  [[Menu.Main]]
    Name = 'photos'
    identifier = "photos"
    # pre = "photo"
    URL = '/photos/'
    weight = 4
  [[Menu.Main]]
    Name = 'categories'
    identifier = "categories"
    URL = '/categories/'
    weight = 5
  [[Menu.Main]]
    Name = 'tags'
    identifier = "tags"
    URL = '/tags/'
    weight = 6
  [[Menu.Main]]
    Name = 'about'
    identifier = "about"
    # pre = "user"
    URL = '/about/'
    weight = 7

# full top bottom left right

# [related]
#   threshold= 80
#   includeNewer= false
#   toLower= false
#   [indices]
#   - name: keywords
#     weight: 100
#   - name: date
#     weight: 10
